### PR TITLE
[Merged by Bors] - add support for listing symbols in a file

### PR DESCRIPTION
**Pull request by eric-wieser**
See https://github.com/leanprover/vscode-lean/pull/305 for the payoff

### CODE REVIEW

**Comment by gebner** [comment]
> I'm not sure how best to test this

You could add a test like this one: https://github.com/leanprover-community/lean/blob/38b59111b2b4e6c572582b27e8937e92fc70ac02/tests/lean/interactive/info_import.input

**Comment by eric-wieser** [comment]
Having through about this a little more, the "what type is this" characterizations probably  should leak through to the autocompletion API; I'll split out a PR to do that once I have my build systems set up again.

**Comment by eric-wieser** [comment]
@gebner: this has changed a little bit, are you still happy with it? The downstream PRs are up to date with the new version.

**Comment by gebner** [comment]
lgtm
bors r+

**Pull request closed without merging**
