### PR TITLE
fix(library/type_context): do not unfold irreducible definitions when trying to unify/match types

### PR DESCRIPTION
**Pull request by bryangingechen**
Fix copied from https://github.com/kha/lean4/commit/f8cedb33e70c9d90c9d81a542340bba0b504f8e6.

See discussion: https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/witt.20vectors/near/169124238

### CODE REVIEW

**Comment by gebner** [comment]
Here's the actual Lean 4 code: https://github.com/leanprover/lean4/blob/7899ab3761f4061f0699e6922102f4abf401f3be/src/Init/Lean/Meta/ExprDefEq.lean#L229-L238

**Comment by bryangingechen** [comment]
Interesting. Does the Lean 4 code behave similarly to this PR? 

What's the next step here? Since this PR breaks [a number of proofs in mathlib](https://gist.github.com/bryangingechen/8ebb9400835b54482f4d2246501f94be), is there something else in core that should be adjusted?

**Comment by gebner** [comment]
I think the new Lean 4 code dies exactly the same thing.

Are the errors in mathlib fixable?  Let's merge this if it doesn't introduce any unsurmountable problems.

**Comment by bryangingechen** [comment]
I've opened a branch https://github.com/leanprover-community/mathlib/tree/lean_pr_211 with a few fixes. I'll update the gist above marking the errors I've fixed.

There's more discussion about this happening in [this Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/144837-PR-reviews/topic/lean.23211.20don't.20unfold.20irred.20defs).

**Pull request merged**
