### PR TITLE
[Merged by Bors] - feat(library/type_context): tc synth with mvar in type

### PR DESCRIPTION
**Pull request by gebner**

### CODE REVIEW

**Comment by Kha** [comment]
You might be interested in https://github.com/leanprover/lean4/commit/18a89abbe6d0f0528195462098a4663f5c952275 :)

**Comment by gebner** [comment]
Note that this a fairly safe change, since the elaborator only calls type class synthesis for goals that do not have metavariables (except for `out_params`).  So this should only really affect coercions to functions/types, or manual calls to `mk_instance`.

mathlib builds without a single error.

For completeness, I'll also try to disable the corresponding check for standard coercions.

**Comment by gebner** [comment]
mathlib still builds.

**Comment by gebner** [comment]
bors merge

**Pull request closed without merging**
