### PR TITLE
fix(tactic/apply_tactic): solve instances in forward order

### PR DESCRIPTION
**Pull request by rwbarton**
This fixes an issue with rw discussed at
https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/rewriting.20and.20type.20class.20inference/near/176608876.

### CODE REVIEW

**Comment by rwbarton** [comment]
I suppose the responsible thing to do is to add a test case, I'll write one in a bit.

**Comment by rwbarton** [comment]
I don't understand why Travis claims the emscripten build failed--I guess I'll try restarting it again (I already tried once).

**Comment by bryangingechen** [comment]
It looks like it happened with [this build too](https://travis-ci.org/leanprover-community/lean/jobs/590120979). 

One difference I noticed is the `kill %1` command doesn't return any output on the broken builds [1](https://travis-ci.org/leanprover-community/lean/jobs/590058488#L2922) [2](https://travis-ci.org/leanprover-community/lean/jobs/590120979#L3007), whereas it did previously: cf. [the last working build](https://travis-ci.org/leanprover-community/lean/jobs/589621216#L3008).

So maybe the `while sleep 5m` [in `.travis.yml`](https://github.com/leanprover-community/lean/blob/master/.travis.yml#L140-L142) might be failing to terminate and killing the build.

**Comment by bryangingechen** [comment]
There's now a fix for the travis issue in #68.

**Comment by gebner** [comment]
No regressions on mathlib, let's get this in.

**Pull request merged**
