### PR TITLE
feat(io/serial): add `expr` serialization/deserialization functions

### PR DESCRIPTION
**Pull request by khoek**
Add `meta def serialize : handle → expr → io unit` and `meta def deserialize : handle → io expr` with the expected semantics.

### CODE REVIEW

**Comment by cipher1024** [comment]
Why does this need to be in Lean itself?

**Comment by khoek** [comment]
Ultimately, speed. After multiple attempts at parsing a string serialised format from within lean (the fastest is on my github under `leancache`), I ran into two major roadblock problems: 1. manipulating strings and in particular doing string IO can be really slow from within lean, for instance appending to a `buffer char` can take ludicrously long times when dealing with megabyte sized stuff and 2. even in crafted situations where I could avoid the IO problems, just parsing serialised strings and constructing the nested `expr`s takes a really disappointing amount of time.

I used to have hard comparison numbers but I'm pretty sure I've lost them(?), but the bottom line is that in my testing C++ serialisation/deserialisation of the same thing vs within lean was a factor of 1000 times faster, with examples taking say 6-10 in editor from within lean, and <10 milliseconds with a native implementation. It was so bad that I totally gave up doing it from within lean.

Actually, to be honest, UTF8 transcoding big pieces of data can suffer from point (1) above too, which is why I didn't end up investing too much time in writing good lean support for it back when I was interested in it.

**Comment by khoek** [comment]
On the other hand, the C++ implementation is *really* fast. Massive proofs in tens of milliseconds. I think it could be life-changing.

**Comment by khoek** [comment]
Fixed up the whitespace making the linter fail.

**Pull request merged**
