### PR TITLE
[Merged by Bors] - chore(data/fin): make fin a subtype

### LINKED ISSUE #359: `fin n` should be a subtype
I just got frustrated because I couldn't use `subtype.forall` on `fin n`.
We should turn `fin n` into a subtype.

### PR DESCRIPTION
**Pull request by jcommelin**
fixes #359

### CODE REVIEW

**Comment by gebner** [comment]
The tests fails.

**Comment by jcommelin** [comment]
I've tried to fix the tests (-;

**Comment by jcommelin** [comment]
@gebner Locally the build + tests are totally fine. But CI is complaining. I don't know what's going on.

**Comment by gebner** [comment]
CI is green BTW.

**Comment by jcommelin** [comment]
Ooh, silly me. Looking at the wrong GH notification :facepalm:

**Comment by gebner** [comment]
bors merge

**Pull request closed without merging**
