### PR TITLE
Fix some cases when adding lean language to the start of a code block

### PR DESCRIPTION
**Pull request by ratmice**
The commit message for fb74ebb basically covers the before and after,
Not all doc strings were being checked for balance,

The first commit fixes the unbalanced doc strings that were in core
before the patch, since now those doc strings will cause an error.

Further some doc strings, containing an "info string", (e.g. language),
were in some cases being mangled, when trying to add the default lean language.
because it only recognized doc strings immediately followed by white space as the start
of a code block.

### CODE REVIEW

**Comment by ratmice** [comment]
Just remembered I forgot to compile mathlib, it quite possibly has the same sort of issue as 00fdee1

**Comment by cipher1024** [comment]
Can you try using this feature to build mathlib? If it doesn't break too badly, we can get this into `3.5.0c`

**Comment by ratmice** [comment]
Will do it in the morning.

**Comment by ratmice** [comment]
@cipher1024 
mathlib compiled without issue, the resulting doc_strings in the .olean were the same,
and the rather naive lookahead in the patch didn't appear to affect compile times.

**Comment by cipher1024** [comment]
Nice, thank you. It seems like the only thing left to fix is your coding style. Travis gave those errors:

```
/home/travis/build/leanprover-community/lean/src/library/documentation.cpp:132:  Tab found; better to use spaces  [whitespace/tab] [1]
/home/travis/build/leanprover-community/lean/src/library/documentation.cpp:133:  Tab found; better to use spaces  [whitespace/tab] [1]
/home/travis/build/leanprover-community/lean/src/library/documentation.cpp:134:  Tab found; better to use spaces  [whitespace/tab] [1]
/home/travis/build/leanprover-community/lean/src/library/documentation.cpp:135:  Tab found; better to use spaces  [whitespace/tab] [1]
/home/travis/build/leanprover-community/lean/src/library/documentation.cpp:137:  Tab found; better to use spaces  [whitespace/tab] [1]
/home/travis/build/leanprover-community/lean/src/library/documentation.cpp:138:  Tab found; better to use spaces  [whitespace/tab] [1]
/home/travis/build/leanprover-community/lean/src/library/documentation.cpp:139:  Tab found; better to use spaces  [whitespace/tab] [1]
/home/travis/build/leanprover-community/lean/src/library/documentation.cpp:141:  Tab found; better to use spaces  [whitespace/tab] [1]
/home/travis/build/leanprover-community/lean/src/library/documentation.cpp:142:  Tab found; better to use spaces  [whitespace/tab] [1]
/home/travis/build/leanprover-community/lean/src/library/documentation.cpp:144:  Tab found; better to use spaces  [whitespace/tab] [1]
/home/travis/build/leanprover-community/lean/src/library/documentation.cpp:145:  Tab found; better to use spaces  [whitespace/tab] [1]
/home/travis/build/leanprover-community/lean/src/library/documentation.cpp:146:  Tab found; better to use spaces  [whitespace/tab] [1]
/home/travis/build/leanprover-community/lean/src/library/documentation.cpp:147:  Tab found; better to use spaces  [whitespace/tab] [1]
```

**Comment by ratmice** [comment]
@cipher1024 So, that seemed to work, except the 1 error with the clang-3.4, travis image, 
but it doesn't appear to be anything I resolve afaict.

**Pull request merged**
