### PR TITLE
[Merged by Bors] - chore(library/init/data/nat): backport Nat.le from Lean4

### PR DESCRIPTION
**Pull request by semorrison**
The corresponding PR to mathlib is https://github.com/leanprover-community/mathlib/pull/8756.

### CODE REVIEW

**Comment by gebner** [comment]
The reason for the timeouts seems to be related to strings:
```lean
set_option profiler true
example (h : 'h' = 'w') : false := by cases h -- before and now 0.4s
example (h : "h" = "w") : false := by cases h -- before 0.5s, now 7s
example (h : ['h'] = ['w']) : false := by cases h -- before 0.4s, now 2.7s
```

From what I can tell, this is because Lean tries to unify `104 < 0xd800` and `119 < 0xd800`.  This used to be fast (and not unifiable), but now it requires computing the inequality (and it's also unifiable now!).

**Comment by fpvandoorn** [comment]
would it make sense to make `nat.ble` irreducible?

**Comment by gebner** [comment]
I'd rather make `nat.le` irreducible.  Making `nat.ble` irreducible means you can't use it in `dec_trivial` anymore.

**Pull request closed without merging**
