### PR TITLE
Do Nothing

### PR DESCRIPTION
**Pull request by khoek**
See if master really doesn't compile by making travis go again.

### CODE REVIEW

**Comment by khoek** [comment]
https://github.com/leanprover-community/lean/pull/19 compiles on top of master, so I figure it was just a travis muck up

**Comment by khoek** [comment]
Yeah, it all looks fine to me.

**Comment by khoek** [comment]
@digama0 I don't know if that's a joke, but are you able to re-run travis on master? If failed on osx randomly last time

**Comment by khoek** [comment]
Oh ok you did sweet

**Comment by digama0** [comment]
that was a joke.

**Comment by cipher1024** [comment]
That's curious. I re-ran it a couple of times before asking for help.

**Pull request closed without merging**
