### PR TITLE
[Merged by Bors] - chore(init/meta/interactive): allow propagate_tags to be used interactively

### PR DESCRIPTION
**Pull request by eric-wieser**

### CODE REVIEW

**Comment by eric-wieser** [comment]
Alarmingly the mac build is segfaulting on test 480...

**Comment by gebner** [comment]
bors r-
bors cancel

**Comment by gebner** [comment]
Oh wait, it worked when bors ran the CI.  So this is indeed alarming since it happens nondeterministically.

bors r+

**Pull request closed without merging**
