### PR TITLE
feat(interactive): add def for parsing raw `expr`s

### PR DESCRIPTION
**Pull request by khoek**
Since we have all the machinery to get the parser to report the underlying reflected `expr`s instead of evaluating them, I should have included a function which let you ask that a parser return this information (the `expr`) for you.

### CODE REVIEW

**Comment by cipher1024** [comment]
Is this ready?

**Comment by khoek** [comment]
Yep, it is. Typeclass resolution and the instances in the last pull do the rest of the job. You can see an example of what you can do now in the tests.

**Comment by cipher1024** [comment]
Cool! When you call `./test_single.sh` on it, you can generate a file for the expected output. That would be interesting to have in git and it would be a more complete test. You do it with `./test_single.sh path/to/lean/binary test_file.lean yes`. Please do that and I'll merge.

**Comment by khoek** [comment]
@cipher1024 Hopefully I've now done what you wanted. But travis has broken itself with some failed apt-get business

**Pull request merged**
