### PR TITLE
Fix building with GCC 9.1.0

### LINKED ISSUE #62: VM assertion failure when building the standard library
### Description

I am reliably unable to build the Lean standard library with a Release build of the master branch and get this error:
```
terminate called after throwing an instance of 'lean::exception'
  what():  vm check failed: is_composite(o) (possibly due to incorrect axioms, or sorry)
```
It also seems to happen [on MinGW](https://ci.appveyor.com/project/cipher1024/lean-e5aoi/builds/27002887/job/pkp6cl1q3t4wf5xk), and it has been mentioned on Zulip.

Using Lean in single-threaded (`-j1`) mode doesn't help, which makes me think this is not a race condition. Combined with the fact that both of

- building Lean in Debug mode
- using the Nightly binary from `elan`

**do** work, I'm thinking this is undefined behaviour that happens to work sometimes if the compiler does the right undefined thing.

### Steps to Reproduce
1. Build Lean with `-DCMAKE_BUILD_TYPE=RELEASE`
2. Try to `../bin/lean --make` in the `library/` folder

### Versions

Lean (version 3.5.0, commit 014fd370b128, RELEASE)
Arch Linux, GCC 9.1.0

### PR DESCRIPTION
**Pull request by Vtec234**
Fixes #62

### CODE REVIEW

**Comment by cipher1024** [comment]
This looks good! Any reasons for the changes outside of `CMakelists.txt`? They look superfluous.

What is the consequence on performance of disabling this feature? I assume it's an optimization.

**Comment by Vtec234** [comment]
@cipher1024 I introduced the changes when searching for this bug to silence some annoying `-Wpedantic` warnings. Mostly cosmetic, but they don't hurt. The JSON update did break emscripten, so I reverted it just now.

I'm not sure how to benchmark of this - I don't suppose we have something like Lean 4's [speedcenter](http://speedcenter.informatik.kit.edu/lean/)? Anyway I can conjecture that this won't have any significant impact, because the flag disables the most specific pass it can - [ifcombine](https://github.com/gcc-mirror/gcc/blob/master/gcc/tree-ssa-ifcombine.c#L51). In effect, statements like `if (a > b) { if (a > c) { ` will not be combined into one, but all the other optimizations will still be done.

**Comment by cipher1024** [comment]
I haven't seen that tool used with Lean 3. If you feel like setting it up, that would be great. Otherwise, that explanation sounds good to me.

**Comment by Vtec234** [comment]
Oof, I'm afraid setting that up would be outside my jurisdiction. But hopefully there will be no observable difference and anyway we can remove the flag when a fixed GCC is released.

**Comment by cipher1024** [comment]
That's alright. Which Travis / appveyor builds test your changes?

**Comment by Vtec234** [comment]
The only build that uses GCC 9.1.0 is [the AppVeyor MinGW one](https://ci.appveyor.com/project/cipher1024/lean-e5aoi/builds/27050814/job/04wbejvc3su9beuc).

**Comment by cipher1024** [comment]
Any chance it might also fix #59?

**Comment by Vtec234** [comment]
It seems to have [failed for the same reason](https://ci.appveyor.com/project/cipher1024/lean-e5aoi/builds/26836597/job/a0p7ulnskt0e1arb), so yeah, probably.

**Comment by cipher1024** [comment]
It did solve it, thanks! Can you revert the `;` changes? I'd like to limit the number of files this PR touches. I'll merge after.

**Comment by Vtec234** [comment]
Why limit the number of files? I'm not clear on why that would be helpful.

**Comment by cipher1024** [comment]
Because the changes create noise in the git history. Minimizing the changes makes it easier to read a commit and see what it's about.

**Comment by Vtec234** [comment]
Ah right, that's true. I split it into two commits to make them clearer.

**Comment by cipher1024** [comment]
Oh! I didn't think they were necessary! If we need them, that's ok to keep them in one commit. It will encapsulate the whole solution to the problem.

**Comment by Vtec234** [comment]
@cipher1024 To be clear, the `;`s were *not* needed for this fix. They just happened to have been the easiest-to-fix out of the warnings I sifted through looking for this bug, being a syntactic change that can't affect program meaning. It should have then been two commits, but I'm personally mildly opposed to trying to keep a pristine git history, because at some point the process adds significant overhead and becomes more trouble than it's worth. So I say a "good-enough" history is fine - as long as every meaningful change is noted, sneaking in minutiae like these on the side is acceptable.

**Comment by cipher1024** [comment]
Like everything else, there is a point where putting more time cleaning up the git history yields no return. The question is when does this occur. In this situation, I was under the impression that adding the `;` had no effect (as opposed to removing warnings) so it looked like pure noise to me which seems worth dismissing (a bit like an arbitrary change in spacing in an unrelated commit). 

Since getting rid of the warnings was part of your investigation of the bug, I think it's ok to keep them together or separate them. As you say, going on and on about that decision is not that useful.

**Pull request merged**
