### PR TITLE
chore(init/data/set): Delete

### PR DESCRIPTION
**Pull request by YaelDillies**
To be (obviously!) restored on the mathlib side. Followup to #675

### CODE REVIEW

**Comment by fpvandoorn** [comment]
> Feel free to move the rest to mathlib as well. Except for `set_of` because that's referenced by Lean.

Should we leave `set_of` here?

**Comment by YaelDillies** [comment]
Oh, I missed this. Where is it referenced?

**Comment by fpvandoorn** [comment]
Probably in the C++ code, on how to parse `{ ... | ... }`.

**Comment by gebner** [comment]
I believe `set_of` is the only reason some of the `set` definition is still in core.  There's also a test that checks whether every definition referenced from the C++ side actually exists in the library:
bors try

**Comment by fpvandoorn** [comment]
Relevant line in the build failure: `init.data.basic` cannot find `init.data.set`.

**Comment by eric-wieser** [comment]
bors try

**Comment by eric-wieser** [comment]
Looks like there are 24 failing tests (search for `***Failed` in the logs to find them)

**Comment by YaelDillies** [comment]
This probably won't happen now that Lean 4 is out.

**Pull request closed without merging**
