### PR TITLE
feat(library/init/data/sum/basic): add projections out of sum

### PR DESCRIPTION
**Pull request by JLimperg**
This commit adds

- `get_left : α ⊕ β → option α`
- `get_right : α ⊕ β → option β`
- `is_left : α ⊕ β → bool`
- `is_right : α ⊕ β → bool`

### CODE REVIEW

**Comment by gebner** [comment]
Is there a reason this can't go into mathlib instead?

**Comment by JLimperg** [comment]
None in particular. The generic reason why I PR'd them here is that I feel like basic functions should be in core so that it remains/becomes possible to use Lean without a 150k LOC dependency.

**Comment by gebner** [comment]
Unless they are needed for something else in core, please PR them to mathlib instead.

**Comment by JLimperg** [comment]
All right, will do.

**Pull request closed without merging**
