### PR TITLE
fix(tactic/revert_lst): check that the provided expressions are variables

### PR DESCRIPTION
**Pull request by cipher1024**
# Pull Request Description

Ensure you have read the contribution guide before filling in a description of the
pull request, regardless of whether it is complete or a work in progress.
All Pull Requests should include test case(s) which demonstrates the intended
behavior of a feature, or a regression test demonstrating that the fix resolves
the issue.

### CODE REVIEW

**Comment by khoek** [comment]
Small mistake in your test. It's fixed in https://github.com/khoek/klean/tree/fix-revert

**Comment by cipher1024** [comment]
thanks!

**Comment by khoek** [comment]
Do we have any idea what is going on with the rando-failures? Travis is just killing the `ctest` process, right?

**Comment by cipher1024** [comment]
There's something weird going on with this build. Can anyone see why that is?

**Pull request merged**
