### PR TITLE
fix(test/non_meta_rec_fn): fix flaky test by not checking stdout

### PR DESCRIPTION
**Pull request by Vierkantor**
# Pull Request Description

The test `non_meta_rec_fn` checks soundness of Lean when defining a generally recursive function in a tactic block, by verifying this gives an error.  In CI there were some failures (e.g. https://travis-ci.org/leanprover-community/lean/jobs/643558684) because the error message given by `non_meta_rec_fn` did not have a consistent column number (but was otherwise consistent). To make the tests less flaky, moving it to the fail tests should check that the definition is invalid, while not being as strict about the precise error message.

### CODE REVIEW

**Comment by cipher1024** [comment]
We're losing a lot of details by doing that. If the error message changes by accident, we won't be warned.

**Comment by bryangingechen** [comment]
Related issue: #72. Out of curiosity, does anyone have any insight into why the column number would be inconsistent here?

**Comment by gebner** [comment]
My pet theory is the following: while the position of an expression is stored in the expression itself, the position does not factor in the hash code or equality checks (it is also mutable IIRC).  We probably just deduplicate expressions somewhere, and replace the expression with one position with another (equal!) expression with a different position.

**Comment by gebner** [comment]
I think this is a good and pragmatic change and believe that we should merge it.

The important part about this test is just that it fails, not the precise wording of the error message.  While it would be nice to fix the nondeterministic column on macOS instead, I'm not sure this is realistic given our resources or even a good use of our time.

**Comment by cipher1024** [comment]
What worries me about this change is not so much about losing a test for the wording but losing an indication of the proof state that gets reported. If an error gets introduced in wf recursion such that the goal gets messed up, this is one of the safeguards that could warn us.

**Comment by gebner** [comment]
I think we have quite a few other tests for well-founded recursion (including error messages), this test specifically tests for a apparent inconsistency in Lean one or two years ago.

**Comment by gebner** [comment]
And the problem reappeared in the darwin build for #122.

**Pull request merged**
