### PR TITLE
[Merged by Bors] - fix(library/init/data/nat/lemmas): fix vacuous assumptions in nat lemmas

### PR DESCRIPTION
**Pull request by jcommelin**

### CODE REVIEW

**Comment by bryangingechen** [comment]
There's an extra argument to `nat.mul_lt_mul'` here:

https://github.com/leanprover-community/lean/pull/366/files#diff-d3d17d9ef912378c84ec927e3808bda9R1305

[See the build failure](https://github.com/leanprover-community/lean/pull/366/checks?check_run_id=818639579#step:5:992).

**Comment by jcommelin** [comment]
Weird, I thought I had caught that one.

**Pull request closed without merging**
