### PR TITLE
[Merged by Bors] - chore(library/init/function): use dot notation, add some docstrings

### PR DESCRIPTION
**Pull request by urkud**
Renamed (in `function` namespace):

* `injective_comp`, `surjective_comp`, `bijective_comp`: `injective.comp`, `surjective.comp`, `bijective.comp`;
* `injective_of_left_inverse` : `left_inverse.injective`;
* `injective_of_has_left_inverse`: `has_left_inverse.injective`;
* `surjective_of_has_right_inverse`: `has_right_inverse.surjective`;
* `right_inverse.surjective (new);
* `id_of_left_inverse`, `id_of_right_inverse`: `left_inverse.id`, `right_inverse.id` (both `protected`).

### CODE REVIEW

**Comment by urkud** [comment]
Test `tests/lean/doc_strings.lean` fails because it outputs docstrings of all loaded modules thus assumes that no files in `prelude` have module docs. What is the correct fix: `filter` the list before printing it? Something else?

**Comment by gebner** [comment]
> What is the correct fix: `filter` the list before printing it? Something else?

I would remove the `olean_doc_strings` line.  The `module_doc_strings` is already a function that filters `olean_doc_strings`.

**Comment by urkud** [comment]
BTW, should we move some of these lemmas to `mathlib` instead?

**Comment by gebner** [comment]
bors merge

**Pull request closed without merging**
