### PR TITLE
VM float cleanup

### PR DESCRIPTION
**Pull request by gebner**
Fix the finalization order of the `vm_float` module and rename `mk_vm_float` to `to_obj` according to the naming convention.

### CODE REVIEW

**Comment by cipher1024** [comment]
Why does the order matter?

**Comment by gebner** [comment]
The order only matters for consistency.  In practice there is no issue here since all the finalizers are empty.  It would make a difference for example if `finalize_vm_float` tried to remove the built-in functions added `initialize_vm_float`: the `g_vm_cbuiltins` map storing the built-in functions is freed in `finalize_vm_core`, and then `finalize_vm_float` would segfault if run in the wrong order.

**Comment by cipher1024** [comment]
Ok. Just to confirm, this PR has no effect on the behavior. Is that correct?

**Comment by gebner** [comment]
Yes, there should be no effects on the runtime behavior.  I wanted to create a vm_float, and happened to notice the wrong finalization order (as well as the missing `to_obj` function in the header file).

**Pull request merged**
