### PR TITLE
[Merged by Bors] - fix(init/meta/interactive_base): Use `}}` in format

### PR DESCRIPTION
**Pull request by digama0**
As [discussed on Zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/curly.20braces/near/261185802). This way, escaped braces are balanced. That is, `format!"a{{b}}c"` produces `"a{b}c"`, instead of `format!"a{{b}c"`. Unbalanced braces are bad for editors and formatters, so we should not encourage any syntax that requires unbalanced braces.

### CODE REVIEW

**Comment by kmill** [comment]
It seems like the only modules in mathlib this will obviously affect are in `src/tactic`: `core.lean`, `monotonicity/interactive.lean`, `pretty_cases.lean`, `squeeze.lean`, and `transfer.lean`.

Mathlib seems to have its own version of `format!`, too, in `src/tactic/core.lean` (see `parse_pformat`), which is used in the `trace!` macro, and `src/tactic/simps.lean` has a case of `{{`.  (I'm not sure I didn't miss anything.)

**Comment by digama0** [comment]
I expect very few changes in mathlib. `format!` and friends are used rarely, and `{{` in format even more rarely. I was planning to defer this until after it lands and we are working on the mathlib bump PR, but this should be an exhaustive enumeration: [1](https://github.com/leanprover-community/mathlib/blob/master/src/tactic/core.lean#L1475) [2](https://github.com/leanprover-community/mathlib/blob/master/src/tactic/core.lean#L1694) [3](https://github.com/leanprover-community/mathlib/blob/master/src/tactic/pretty_cases.lean#L56) [4](https://github.com/leanprover-community/mathlib/blob/master/src/tactic/squeeze.lean#L53) [5](https://github.com/leanprover-community/mathlib/blob/master/src/tactic/transfer.lean#L74) [6](https://github.com/leanprover-community/mathlib/blob/master/src/tactic/monotonicity/interactive.lean#L65), plus the implementation of `pformat!` has to be updated.

**Comment by gebner** [comment]
I agree with the balancing philosophy, and wholeheartedly approve of the whitespace formatting.

bors r+

**Pull request closed without merging**
