### PR TITLE
refactor(algebra/field): get rid of discrete_field

### PR DESCRIPTION
**Pull request by ChrisHughes24**
This PR gets rid of `discrete_field` and adds `inv_zero` as an axiom of a `division_ring`.

It also removes the superfluous `inv_mul_cancel` axiom of a field

# Pull Request Description

Ensure you have read the contribution guide before filling in a description of the
pull request, regardless of whether it is complete or a work in progress.
All Pull Requests should include test case(s) which demonstrates the intended
behavior of a feature, or a regression test demonstrating that the fix resolves
the issue.

### CODE REVIEW

**Comment by rwbarton** [comment]
> What fallout do we expect from this change in mathlib? Is it clear what we need to do in mathlib?

Probably just replace all occurrences of `discrete_field` by `field`.

**Comment by digama0** [comment]
It's not just a name change, the change to division rings might have some fallout, but I think we have done almost nothing with division rings so this should be mostly just a find/replace job.

**Comment by jcommelin** [comment]
Note that this change is in some sense quite important. Currently, in Lean you can have two division ring structures on a type that are provably *not* equal (after applying ext, etc...), whereas they are mathematically identical. The difference would be that in maths `inv zero` doesn't make any sense, whereas in Lean one of the structures could have `inv zero = one` and the other `inv zero = zero`. This fact is actually blocking the generalisation of a bunch of simp-lemmas from fields to division rings.

**Comment by gebner** [comment]
The build fails in `ordered_field.lean`.

**Comment by gebner** [comment]
Now it fails in `norm_num.lean`.

**Comment by fpvandoorn** [comment]
* I think this PR should also get rid of (or at least rename) `discrete_linear_ordered_field`.
* Should we add a `decidable_eq` instance to the fields of `field`? I think we have a couple of choices:
  1. We don't add `decidable_eq`, and just use classical logic to get `decidable_eq` instances
  2. We don't add `decidable_eq`, but add it as an instance whenever needed.
  3. We add `decidable_eq` to `field`.

  These choices matter if we do constructive logic, but I don't think anyone cares about this too much. However, they might also matter when doing classical logic. For example, if there is an instance `linear_ordered_field -> decidable_linear_order` which uses `classical.prop_decidable` then we might have two instances of `decidable_linear_order rat`, one where `decidable_le` (and variants) is proven, and one where it is a consequence of `classical.prop_decidable`. That could lead to potential fallout (for example: locally changing an instance priority might make all lemmas involving `max` not apply anymore).

**Comment by ChrisHughes24** [comment]
Another option is to make `max` and `abs` fields of the structures and get rid of the `decidable_eq` assumptions. There are examples where there was a diamond where `sup` was not the same as `max` on `with_top` of a linear order. I think there should perhaps be a `has_abs.abs` that includes the `abs` on complexes perhaps? I'd be happy to rename `max` to `sup` as well.

**Comment by digama0** [comment]
Why not use the lattice operations for this? `max` coincides with `sup` whenever the former is defined, and `abs` coincides with `max x (-x)` in the current definition but we also might want it to look like `norm` in some cases. But `norm` is real valued while `abs` is valued in the structure, so I don't know what the right generalization is.

**Comment by gebner** [comment]
This change seems to require a bit more discussion, is everybody OK with delaying it until Lean 3.7?

**Comment by jcommelin** [comment]
> This change seems to require a bit more discussion, is everybody OK with delaying it until Lean 3.7?

Let's at least add `inv_zero` to `division_ring`. That should be completely uncontroversial.

**Comment by jcommelin** [comment]
> This change seems to require a bit more discussion, is everybody OK with delaying it until Lean 3.7?

Let's at least add `inv_zero` to `division_ring`. That should be completely uncontroversial.

**Comment by ChrisHughes24** [comment]
I think everything in this PR should be uncontroversial. The part that requires discussion is what to do with ordered rings and fields, but this PR does nothing to them.

**Comment by gebner** [comment]
Ok, then let's get this in.  I've merged master into the branch and everything builds locally.  Let's wait for the CI.

**Comment by gebner** [comment]
One test failed (the C++ code uses the norm_num helper lemmas to construct proofs, and you removed one unnecessary argument).  I've fixed this so that we can merge this ASAP.

**Pull request merged**
