### PR TITLE
[Merged by Bors] - chore(data/nat): remove nat.pow

### PR DESCRIPTION
**Pull request by rwbarton**
mathlib will use `monoid.pow` to supply `has_pow nat nat`.
The removed lemmas will be migrated to mathlib
(and their proofs adjusted as needed)
along with the module `data.bitvec`.

### CODE REVIEW

**Comment by rwbarton** [comment]
I have a sorry-free (and actually not too painful) version of mathlib that builds against this patch applied to 3.18.4 (current mathlib doesn't build with current Lean yet).

**Comment by jcommelin** [comment]
Does this mean that we don't want GMP VM implementations for nat.pow?

**Comment by rwbarton** [comment]
Well apparently no one wanted to implement that while it was convenient, so making it more difficult doesn't seem like a big problem.

**Comment by bryangingechen** [comment]
> I have a sorry-free (and actually not too painful) version of mathlib that builds against this patch applied to 3.18.4 (current mathlib doesn't build with current Lean yet).

Maybe we could fold that into leanprover-community/mathlib#3955 (and make it "update to version 3.20.0c")?

**Comment by rwbarton** [comment]
My mathlib changes corresponding to the present PR are not ready to be PRed yet, and I'd personally prefer not to hold up leanprover-community/mathlib#3955 more than necessary since I would like to make some unrelated changes to `data.fin`.

**Comment by bryangingechen** [comment]
What a strange error: https://github.com/leanprover-community/lean/runs/1045536694#step:9:210

Let's see if it was just a fluke:
bors r+

**Comment by gebner** [comment]
> [S, E, C, R, E, T, _, D, A, T, A]

:rofl:

**Pull request closed without merging**
