### PR TITLE
[Merged by Bors] - perf(simp_lemmas): cache constructed simp_lemma objects

### PR DESCRIPTION
**Pull request by gebner**
This was a lot easier than I'd imagined because temporary metavariables can be safely serialized.  When the user writes `@[simp]` we simply store all generated simp lemmas in the `_simp_cache` attribute.

### CODE REVIEW

**Comment by gebner** [comment]
I'll compile mathlib with this change to evaluate the performance difference (of running `by simp` after `import all`).

**Comment by gebner** [comment]
There is one unexpected user-facing change: if you set `_refl_lemma` manually, you need to do this before you set the `simp` attribute now.

**Comment by gebner** [comment]
The performance is *nice*:
```
   38ms    46.9%   simp_lemmas.mk_default
```

This is after `import all`.  Unfortunately it segfaults on windows, mac, and emscripten.

**Comment by digama0** [comment]
At least it works on all the important OS's...

**Comment by gebner** [comment]
bors try

**Comment by gebner** [comment]
bors merge

**Pull request closed without merging**
