### PR TITLE
refactor(data/nat/basic): get rid of nat.pow

### PR DESCRIPTION
**Pull request by ChrisHughes24**
This gets rid of the `has_pow nat nat` instance which should be replaced by `monoid.pow`.
I deleted one lemma which should be moved to mathlib. The other deleted lemmas are not specific to natural numbers and should already be proved for `monoid.pow`

# Pull Request Description

Ensure you have read the contribution guide before filling in a description of the
pull request, regardless of whether it is complete or a work in progress.
All Pull Requests should include test case(s) which demonstrates the intended
behavior of a feature, or a regression test demonstrating that the fix resolves
the issue.

### CODE REVIEW

**Comment by ChrisHughes24** [comment]
This breaks `data/nat/bitwise.lean`. Maybe these lemma should be moved to mathlib?

**Comment by gebner** [comment]
> This breaks `data/nat/bitwise.lean`. Maybe these lemma should be moved to mathlib?

I don't think these are used anywhere, so we can probably safely move them to mathlib.

**Comment by cipher1024** [comment]
> > This breaks `data/nat/bitwise.lean`. Maybe these lemma should be moved to mathlib?
> 
> I don't think these are used anywhere, so we can probably safely move them to mathlib.

I can confirm. I believe we PRed this module when I was at Galois. @joehendrix Do you use the Lean 3 community fork at Galois? Is it a problem if `bitvec` moves to `mathlib`?

**Comment by gebner** [comment]
Another issue is that `nat.pow` and the bitwise operations have efficient VM implementations.

**Comment by cipher1024** [comment]
For `nat.pow`, we could use `**` as the notation and not create an instance. We can use it in programs and have a simp rule rewrite it to `^` in proofs.

**Comment by jcommelin** [comment]
> Another issue is that `nat.pow` and the bitwise operations have efficient VM implementations.

Do those VM implementations care about what the definition of `nat.pow` is in Lean? I don't think so, right? So we can make this work, if we want.

**Comment by joehendrix** [comment]
I just saw my name mentioned here.
I don't think anybody at Galois is using Lean 3, and dropping `nat.pow` (or just changing the definition) seems fine to me.  I've always been a bit uncomfortable in general with having definitions that are only efficient because they have VM acceleration that isn't always documented in the Lean source.

**Comment by rwbarton** [comment]
The build failed because these lemmas are used elsewhere in the core library. I'm going to replace this with a new PR.

**Pull request closed without merging**
