### PR TITLE
[Merged by Bors] - refactor(*): remove norm_num

### PR DESCRIPTION
**Pull request by jcommelin**
This PR removes norm_num from core, since there is now a faster implementation in lean in mathlib.

### CODE REVIEW

**Comment by gebner** [comment]
LGTM.  Please choose a PR title that confirms to the naming scheme.  I've also put a few other PRs on the queue, so you will probably need to merge master and update `constants.txt` again in an hour or so.

**Comment by jcommelin** [comment]
@gebner I fixed the conflicts

**Comment by gebner** [comment]
Please run `python3 script/gen_constants_cpp.py src/library/constants.txt`

**Comment by jcommelin** [comment]
Thanks! That script is helpful (-;

**Comment by gebner** [comment]
bors merge

**Pull request closed without merging**
