### PR TITLE
fix(*): make `0 < 0.1` an elaboration error

### PR DESCRIPTION
**Pull request by gebner**
Introduce new type classes for integer division (`/.`) and truncating subtraction (`-.`).  Unfortunately we can't have `//` like in python because of the subtype notation.

The division breaks surprisingly little, the subtraction breaks a bit more but it's really easy to fix.

### CODE REVIEW

**Comment by fpvandoorn** [comment]
***If*** this is the right way to go:
* What does `0 < 0.1` mean after this change? Error, cannot find `has_div` instance on `nat`? Or is it actually an inequality in `rat` (once `rat` is defined)?
* I prefer [monus](https://en.wikipedia.org/wiki/Monus) `∸` over `-.`
* Before this merges, we need to at least add some doc strings to the new classes.

**Comment by gebner** [comment]
> What does `0 < 0.1` mean after this change?

It is an elaboration error (`failed to synthesize type class instance for has_div ℕ`).  It is not easy to change the algorithm to default the number type.  (Although I guess we could hack it to pick different types depending on which type classes we need to synthesize...)

**Comment by cipher1024** [comment]
Should we use `÷` instead of `/.`?

**Comment by PatrickMassot** [comment]
I'm not sure at all this is a desirable change. I would much prefer to see more efforts on the automation side than weird notations. I understand it's a huge effort, but fixing `omega` so that it can prove more lemmas about nat subtraction, and fixing the parser so that `0.1` is not silently turned into a nat would be much more useful. I don't see any situation where I would want `0.1` to be anything by a rational number, ready to be coerced to any other field if needed.

**Pull request closed without merging**
