### PR TITLE
[Merged by Bors] - chore(library/data/vector): remove global notation for vector.cons

### PR DESCRIPTION
**Pull request by jcommelin**

### CODE REVIEW

**Comment by rwbarton** [comment]
I guess this looks fine but what about just turning it into `local notation`?

**Comment by jcommelin** [comment]
For some reason it didn't work in that file. I don't understand notation well enough to figure out why it broke.

**Comment by rwbarton** [comment]
Oh, maybe it was because of
```lean
@[simp] theorem to_list_cons (a : α) (v : vector α n) : to_list (a :: v) = a :: to_list v := ...
```
I think local notation might just always be preferred to global notation, with no fallback on type errors.

Anyways, LGTM as is.

**Review by digama0 — APPROVED** [review]

**Review by fpvandoorn — APPROVED** [review]
I also had to add extra type annotations to `::` recently because of this notation, so I also welcome this change!

**Comment by gebner** [comment]
:tada: Next step: `multiset.cons`

bors r+

**Pull request closed without merging**
